// Generated by CoffeeScript 1.8.0
(function() {
  var BaseModel, Hypervisors, minimatch, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('../../BaseModel');

  _ = require('underscore');

  minimatch = require('minimatch');

  Hypervisors = (function(_super) {
    __extends(Hypervisors, _super);

    function Hypervisors() {
      this.servers = __bind(this.servers, this);
      this.show = __bind(this.show, this);
      this.find = __bind(this.find, this);
      this.all = __bind(this.all, this);
      this.init = __bind(this.init, this);
      return Hypervisors.__super__.constructor.apply(this, arguments);
    }

    Hypervisors.prototype.init = function() {
      return this.type = "compute";
    };

    Hypervisors.prototype.all = function(params, fn) {
      var detail, query;
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("all()");
      if (typeof params === 'function') {
        fn = params;
        params = {};
      }
      query = {};
      if (params.tenant_id) {
        query.context = params.tenant_id;
      } else {
        query.all_tenants = 1;
        query.context = "%context%";
      }
      if (params.detail) {
        detail = "/detail";
      } else {
        detail = "";
      }
      return this.get("%context%/os-hypervisors" + detail, query, (function(_this) {
        return function(data) {
          if (fn) {
            return fn(data);
          }
        };
      })(this));
    };

    Hypervisors.prototype.find = function(params, fn) {
      var _self;
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("find()");
      if (typeof params === 'function') {
        fn = params;
        params = {};
      }
      if (!params.hypervisor_hostname) {
        throw "`hypervisor_hostname` is mandatory";
      }
      _self = this;
      return this.all(params, function(body) {
        var matches;
        matches = [];
        _.each(body.hypervisors, function(hypervisor) {
          _self.debug(hypervisor);
          if (minimatch(hypervisor.hypervisor_hostname, params.hypervisor_hostname)) {
            return matches.push(hypervisor);
          }
        });
        if (fn) {
          return fn(matches);
        }
      });
    };

    Hypervisors.prototype.show = function(params, fn) {
      var _self;
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("show()");
      if (typeof params === 'function') {
        fn = params;
        params = {};
      }
      if (!params.hypervisor_hostname) {
        throw "`hypervisor_hostname` is mandatory";
      }
      _self = this;
      return this.find(params, function(matches) {
        if (matches.length < 1) {
          throw "No results for " + params.hypervisor_hostname;
        } else if (matches.length > 1) {
          throw "" + params.hypervisor_hostname + " returned multiple results";
        } else {
          if (fn) {
            return fn(matches[0]);
          }
        }
      });
    };

    Hypervisors.prototype.servers = function(params, fn) {
      var query;
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("servers()");
      if (typeof params === 'function') {
        fn = params;
        params = {};
      }
      query = {};
      if (!params.hypervisor_hostname) {
        throw "`hypervisor_hostname` is mandatory";
      }
      if (params.tenant_id) {
        query.context = params.tenant_id;
      } else {
        query.all_tenants = 1;
        query.context = "%context%";
      }
      return this.find(params, (function(matches) {
        if (matches.length < 1) {
          throw "No results for " + params.hypervisor_hostname;
        } else if (matches.length > 1) {
          throw "" + params.hypervisor_hostname + " returned multiple results";
        } else {
          return this.get("%context%/os-hypervisors/" + matches[0].hypervisor_hostname + "/servers", query, (function(_this) {
            return function(data) {
              if (fn) {
                return fn(data.hypervisors[0].servers);
              }
            };
          })(this));
        }
      }).bind(this));
    };

    return Hypervisors;

  })(BaseModel);

  module.exports = function(client) {
    return new Hypervisors(client);
  };

}).call(this);
