// Generated by CoffeeScript 1.8.0
(function() {
  var BaseModel, Hypervisor, minimatch, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('../../BaseModel');

  _ = require('underscore');

  minimatch = require('minimatch');

  Hypervisor = (function(_super) {
    var Server;

    __extends(Hypervisor, _super);

    Server = null;

    function Hypervisor(client, hypervisor) {
      this.servers = __bind(this.servers, this);
      this.init = __bind(this.init, this);
      Hypervisor.__super__.constructor.call(this, client);
      Server = require('./Server')(this.client);
      this.id = hypervisor.id;
      this.hostname = hypervisor.hypervisor_hostname;
    }

    Hypervisor.prototype.init = function() {
      return this.type = "compute";
    };

    Hypervisor.prototype.servers = function(params, fn) {
      var query;
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("servers()");
      if (typeof params === 'function') {
        fn = params;
        params = {};
      }
      query = {};
      if (params.tenant_id) {
        query.context = params.tenant_id;
      } else {
        query.all_tenants = 1;
        query.context = "%context%";
      }
      return this.get("%context%/os-hypervisors/" + this.hostname + "/servers", query, (function(_this) {
        return function(data) {
          var servers, _ref;
          servers = [];
          _.each((_ref = data.hypervisors[0].servers) != null ? _ref : [], function(server) {
            var _server;
            _server = Server(server);
            return servers.push(_server);
          });
          if (fn) {
            return fn(servers);
          }
        };
      })(this));
    };

    return Hypervisor;

  })(BaseModel);

  module.exports = function(client) {
    return function(hypervisor) {
      var _hypervisor;
      return _hypervisor = new Hypervisor(client, hypervisor);
    };
  };

}).call(this);
