// Generated by CoffeeScript 1.8.0
(function() {
  var OpenStack;

  OpenStack = require('./OpenStack').OpenStack;

  module.exports = function(options) {
    return new OpenStack(options);
  };

}).call(this);
